### ISSUE TITLE
Update Nuget package for 1.0.0

### ISSUE THREAD

**Issue by chrispaynter** [vlesierse/dotnet-publish-docker#1]
The Nuget package still currently relies on `Microsoft.NETCore.App (>= 1.0.0-rc2-3002702)` would be great to get it updated to use `1.0.0`

**Comment by chrispaynter** [comment]
Currently causes this error during publish:

```
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.0.0-rc2-3002702'.
```

**Comment by vlesierse** [comment]
Thank you for your feedback. I was planning for an update next week. I'll make sure to change this as well to fix the error.

Thnx

**Comment by vlesierse** [comment]
@chrispaynter I've created a new release `1.0.0-preview1` which contains the correct package references and updated the README.md and blog post. Thank you for your feedback.

I'm currently planning the features to be included for the first initial stable release planned for the stable release of the .NET Core Tooling. If you have ideas, feedback or wishes, please let me know.
